### ISSUE TITLE
Overwrites report file in umbrella app

### ISSUE THREAD

**Issue by DerKastellan** [victorolinasc/junit-formatter#14]
Hi.

In my setup junit-formatter is running fine if I run individual test suites in individual apps.

However, when I run "mix test" in an umbrella app containing them all, it simply writes all report files to the same location which means the later test suites overwrite results from the earlier ones.

Maybe it could make subdirectories?

**Comment by DerKastellan** [comment]
PS - this even happens when I give one of the apps in the umbrella its own config.exs with a different file name.

**Comment by cs-victor-nascimento** [comment]
Thanks for reporting @DerKastellan and sorry it took me sometime to reply.

I will look into it (I confess I expected it to work with umbrella...)!

**Comment by cs-victor-nascimento** [comment]
I've published version 1.1.0 with support for umbrella projects. It now generates the report file in `Mix.Project.app_path` instead of build_path. This will allow for several projects to have each their own report.

Please, check it out! I will leave this one open until you confirm it solves your issue.

**Comment by DerKastellan** [comment]
Thank you, works for me. Writes results to ./_build/test/lib/<app name>/test-junit-report.xml :smile:

**Comment by cs-victor-nascimento** [comment]
Can I close this one @DerKastellan ?

**Comment by DerKastellan** [comment]
Yes, please close this.
